version: '3.9'

services:
  database:
    container_name: scheduler-db
    image: mongo:5.0.3
    # restart: always
    ports:
      - 27018:27017
    volumes:
      - scheduler-db:/data/db

  backend:
    container_name: scheduler-backend
    build: ./backend
    ports:
      - 4080:4080
    depends_on:
      - database

  frontend:
    container_name: scheduler-frontend
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  scheduler-db: {}
